### ISSUE TITLE
Can't launch UI

### ISSUE THREAD

**Issue by joxerg** [Puyodead1-Development/WistiaEmbededVideoDownloader#1]
Hi,
Im trying opening "WistiaEmbedDownloader.java" with java.exe but nothing happens, any clues?
Thank you,

**Comment by joxerg** [comment]
> Hi,
> Im trying opening "WistiaEmbedDownloader.java" with java.exe but nothing happens, any clues?
> Thank you,

Nevermind, i found your .JAR release and after updating JDK worked perfect, thank you!!

**Comment by Puyodead1** [comment]
Java files are source code. 
Glad you figured it out! Hope it works okay!
